# Generated by Django 4.2.19 on 2025-03-05 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name/title of the service.",
                        max_length=50,
                        unique=True,
                        verbose_name="Service Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="More info about this service.",
                        verbose_name="Service Description",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Record Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Record Updated At"
                    ),
                ),
            ],
            options={
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recursion_type",
                    models.CharField(
                        choices=[("MON", "Monthly"), ("ANNU", "Annually")],
                        default="MON",
                        help_text="Determine the type of this plan's recursion.",
                        max_length=50,
                        verbose_name="Recursion Type",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("SAR", "SAR")],
                        default="SAR",
                        help_text="Determine the currency of this plan.",
                        max_length=10,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="How much this plan will cost.",
                        max_digits=10,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Record Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Record Updated At"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        help_text="Service related to this plan.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_plans",
                        related_query_name="subscription_plan",
                        to="subscriptions.service",
                        verbose_name="Service",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "unique_together": {("service", "recursion_type", "currency")},
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False,
                        help_text="Determine the subscription status.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Record Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="Record Updated At"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        help_text="Subscription Plan.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        related_query_name="subscription",
                        to="subscriptions.subscriptionplan",
                        verbose_name="Plan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User related to this subscription.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        related_query_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscription",
                "verbose_name_plural": "Subscriptions",
                "unique_together": {("user", "plan")},
            },
        ),
    ]
