# Generated by Django 4.2.19 on 2025-03-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="iteration",
            field=models.IntegerField(default=1, verbose_name="Iteration"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Record Created At"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Record Updated At"),
        ),
    ]
